'use client'

import { useMemo, useState } from 'react'
import { minutesBetween } from '@/lib/utils'
import { apiFetch } from '@/lib/firebase/request'

type Form = { date:string; day:string; week:string; subject:string; className:string; yearForm:string; startTime:string; endTime:string; topic:string; theme:string; standardContent:string; learningStandard:string; performanceStandard:string; studentLevel:string; textbookContext:string; previousLesson:string }
const initial:Form={date:new Date().toISOString().slice(0,10),day:'',week:'',subject:'Bahasa Melayu',className:'6 Amanah',yearForm:'Tahun 6',startTime:'08:00',endTime:'09:00',topic:'',theme:'',standardContent:'',learningStandard:'',performanceStandard:'',studentLevel:'Pelbagai tahap',textbookContext:'',previousLesson:''}

export default function NewRPHPage(){
 const [form,setForm]=useState(initial); const [result,setResult]=useState<any>(null); const [loading,setLoading]=useState(false); const [msg,setMsg]=useState('')
 const duration=useMemo(()=>Math.max(1,minutesBetween(form.startTime,form.endTime)),[form.startTime,form.endTime])
 function update(k:keyof Form,v:string){setForm(x=>({...x,[k]:v}))}
 async function generate(){setLoading(true);setMsg(''); const r=await apiFetch('/api/ai/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,academicWeek:form.week,duration})}); const data=await r.json(); if(!r.ok)setMsg(data.error||'Ralat'); else setResult(data.rph); setLoading(false)}
 async function save(){if(!result)return; const r=await apiFetch('/api/rph',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,academicWeek:Number(form.week)||0,duration,...result,status:'complete'})}); const data=await r.json(); if(!r.ok)setMsg(data.error||'Gagal simpan'); else location.href=`/rph/${data.id}`}
 return <div className="page"><div className="page-header"><div><p className="eyebrow">AI RPH GENERATOR</p><h1>Jana RPH dengan AI</h1><p className="muted">Masukkan konteks sebenar. Sistem akan menyesuaikan aktiviti dengan tempoh {duration} minit.</p></div></div>
 <div className="grid-2"><section className="card form-grid">
 {([['date','Tarikh','date'],['day','Hari','text'],['week','Minggu','number'],['subject','Subjek','text'],['className','Kelas','text'],['yearForm','Tahun / Tingkatan','text'],['startTime','Masa mula','time'],['endTime','Masa tamat','time'],['topic','Tajuk','text'],['theme','Tema','text'],['standardContent','Standard Kandungan','text'],['learningStandard','Standard Pembelajaran','text'],['performanceStandard','Standard Prestasi','text'],['studentLevel','Tahap murid','text'],['textbookContext','Konteks buku teks','text'],['previousLesson','RPH sebelumnya','text']] as const).map(([k,l,t])=><label key={k}>{l}<input type={t} value={form[k]} onChange={e=>update(k,e.target.value)} placeholder={l}/></label>)}
 <button className="primary wide" onClick={generate} disabled={loading}>{loading?'Menjana...':'✨ Jana RPH AI'}</button>{msg&&<div className="error-box">{msg}</div>}
 </section>
 <section className="card preview-card"><div className="section-head"><h2>Pratonton</h2>{result&&<button className="primary" onClick={save}>Simpan RPH</button>}</div>{!result?<div className="empty">Isi maklumat di sebelah dan tekan Jana RPH AI.</div>:<RPHPreview rph={result} form={form} duration={duration}/>}</section></div></div>
}
function RPHPreview({rph,form,duration}:{rph:any,form:Form,duration:number}){const a=rph.activities||{}; return <article className="rph-preview"><h2>RANCANGAN PENGAJARAN HARIAN</h2><p><b>Tarikh:</b> {form.date} &nbsp; <b>Hari:</b> {form.day} &nbsp; <b>Minggu:</b> {form.week}</p><p><b>Mata Pelajaran:</b> {form.subject} &nbsp; <b>Kelas:</b> {form.className} &nbsp; <b>Masa:</b> {form.startTime}–{form.endTime} ({duration} minit)</p>{[['STANDARD KANDUNGAN',rph.standardContent],['STANDARD PEMBELAJARAN',rph.learningStandard],['STANDARD PRESTASI',rph.performanceStandard],['OBJEKTIF PEMBELAJARAN',(rph.objectives||[]).map((x:string,i:number)=><div key={i}>{i+1}. {x}</div>)],['KRITERIA KEJAYAAN',(rph.successCriteria||[]).map((x:string,i:number)=><div key={i}>{i+1}. {x}</div>)],['AKTIVITI PEMBELAJARAN',<div key="a"><p><b>Set Induksi:</b> {a.setInduksi}</p><p><b>Langkah 1:</b> {a.langkah1}</p><p><b>Langkah 2:</b> {a.langkah2}</p><p><b>Langkah 3:</b> {a.langkah3}</p><p><b>Pengayaan:</b> {a.pengayaan}</p><p><b>Pemulihan:</b> {a.pemulihan}</p><p><b>Penutup:</b> {a.penutup}</p></div>],['KAEDAH / STRATEGI PdP',rph.strategy],['PAK21',rph.pak21],['KBAT',rph.kbat],['EMK',rph.emk],['NILAI MURNI',rph.values],['BBM / BAHAN',rph.materials],['PENTAKSIRAN',rph.assessment],['REFLEKSI',rph.reflection]].map(([h,v])=><section key={String(h)}><h3>{h}</h3><div>{v}</div></section>)}</article>}
